version: '3.8'

services:
  task-service:
    image: task-service:latest
    build:
      context: docker
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/taskdb
      DB_USERNAME: postgres
      DB_PASSWORD: "050399"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "050399"
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: